name: analisis_roya
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^10.1.2
  image_picker: ^0.8.9
  path: ^1.8.3
  path_provider: ^2.1.1
  google_ml_kit: ^0.16.2
  get: ^4.6.5
  cached_network_image: ^3.2.3
  dio: ^5.3.2
  syncfusion_flutter_gauges: ^21.2.10
  syncfusion_flutter_charts: ^21.2.10
  fl_chart: ^0.63.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  url_launcher: ^6.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/maps/
